apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackboxexporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackboxexporter
  template:
    metadata:
      labels:
        app: blackboxexporter
    spec:
      containers:
        - name: blackbox-exporter
          image: prom/blackbox-exporter:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9115  # Port interne de Blackbox Exporter
          args:
            - "--config.file=/etc/blackbox_exporter/config.yml"  # Optionnel, pour configurer Blackbox Exporter

---
apiVersion: v1
kind: Service
metadata:
  name: blackboxexporter
spec:
  selector:
    app: blackboxexporter
  type: NodePort
  ports:
    - protocol: TCP
      port: 9115  # Port d'accès interne du cluster
      targetPort: 9115  # Port exposé par le container
      nodePort: 31115  # Port sur lequel le service sera accessible depuis l'extérieur


