apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:


      # Scraping de Prometheus
      - job_name: 'prometheus'
        static_configs:
          - targets: ["192.168.100.243:30003"]  # Remplacez par l'adresse IP et le NodePort de Prometheus

      # Scraping du Node Exporter
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['192.168.100.243:30001']  # Remplacez par l'adresse IP et le NodePort de Node Exporter
          - targets: ['192.168.100.160:30001']

