apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: boardgame-hpa  # Nom du HPA
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment  
    name: boardgame    # 🚀 Cible le Deployment "boardgame"
  minReplicas: 1       # 📌 Minimum 1 pod
  maxReplicas: 6       # 🚀 Peut aller jusqu'à 6 pods
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80  # ⚡ Ajoute des pods si CPU > 80%
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70  # 💾 Ajoute des pods si RAM > 70%
