---
- name: Initialize Kubernetes Master
  hosts: master
  become: yes
  tasks:
    - name: Initialize Kubernetes Cluster
      command: kubeadm init --apiserver-advertise-address=192.168.100.22 --pod-network-cidr=10.32.0.0/12
      register: kubeadm_init
      changed_when: "'To start using your cluster' in kubeadm_init.stdout"
    - debug:
        msg: "{{ kubeadm_init.stdout_lines }}"

    - name: Create kube config directory
      file:
        path: "{{ ansible_user_dir }}/.kube"
        state: directory
        mode: '0755'
      register: kube_dir
    - debug:
        msg: "Kube config directory created at {{ kube_dir.path }}"

    - name: Copy admin.conf to kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "{{ ansible_user_dir }}/.kube/config"
        remote_src: yes
      register: kube_copy
    - debug:
        msg: "admin.conf copied to ~/.kube/config"

    - name: Change ownership of kube config
      command: "chown {{ ansible_user }}:{{ ansible_user }} {{ ansible_user_dir }}/.kube/config"
      register: kube_chown
    - debug:
        msg: "{{ kube_chown.stdout_lines }}"

    - name: Apply Calico Network Plugin
      command: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml      register: calico_apply
    - debug:
        msg: "{{ calico_apply.stdout_lines }}"

    - name: Get Kubernetes Nodes
      command: kubectl get nodes -o wide
      register: k8s_nodes
    - debug:
        msg: "{{ k8s_nodes.stdout_lines }}"

    - name: Generate Join Command
      command: kubeadm token create --print-join-command
      register: join_command
    - debug:
        msg: "Use this command to join workers: {{ join_command.stdout }}"

