# ConfigMap contenant la configuration de Prometheus
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      # Scraping des pods ayant le label app=clinic
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: clinic

      # Scraping du metrics-server via son adresse externe
      - job_name: 'metrics-server'
        static_configs:
          - targets: ['192.168.100.59:443']
        scheme: https
        tls_config:
          insecure_skip_verify: true

      # Scraping de Prometheus lui-même
      - job_name: 'prometheus'
        static_configs:
          - targets: ["192.168.100.59:9090"]

      # Scraping du Node Exporter
      - job_name: 'node-exporter'
        static_configs:
          - targets: ["192.168.100.59:9100"]
