---
# ConfigMap pour la configuration de Prometheus
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: clinic

---
# DaemonSet pour déployer Prometheus sur tous les nœuds
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prometheus
  labels:
    app: prometheus  # Ajout d'un label pour la sélection dans le service
spec:
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.34.0
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
          volumeMounts:
            - mountPath: /etc/prometheus/prometheus.yml
              name: prometheus-config
              subPath: prometheus.yml
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config

---
# Service pour exposer Prometheus en NodePort
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30090  # Choisissez un numéro de port dans la plage des NodePort (30000-32767)
  type: NodePort  # Définit le type du service comme NodePort
  selector:
    app: prometheus  # Ajout du selector pour faire correspondre avec le DaemonSet
