apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      # Scraping de Prometheus
      - job_name: 'prometheus'
        static_configs:
          - targets: ["192.168.100.243:30003"]  # Remplacez par l'adresse IP et le NodePort de Prometheus

      # Scraping du Node Exporter
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['192.168.100.243:30001']  # Remplacez par l'adresse IP et le NodePort de Node Exporter
          - targets: ['192.168.100.160:30001']

      # Scraping du Blackbox Exporter
      - job_name: 'blackbox'
        metrics_path: /probe
        params:
          module: [http_2xx]  # Look for a HTTP 200 response.
        static_configs:
          - targets:
              - http://192.168.100.243:30085
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: 192.168.100.243:31115  # The blackbox exporter's real hostname:port.


      # Scraping du Metrics Server
      - job_name: 'metrics-server'
        metrics_path: /metrics
        scheme: https
        static_configs:
          - targets: ['metrics-server.kube-system.svc:443']
        tls_config:
          insecure_skip_verify: true   # Désactiver la vérification du certificat (à ne faire que dans un environnement contrôlé)
        relabel_configs:
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: 'metrics-server.kube-system.svc:443'
